export const FETCH_IMAGES = 'FETCH_IMAGES';
export const CLEAR__IMAGES = 'CLEAR__IMAGES';
export const FETCH_HERO_IMAGE = 'FETCH_HERO_IMAGE';
export const FETCH_RANDOM_IMAGES = 'FETCH_RANDOM_IMAGES';
